server:
  port: 8899

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apts_db?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yeyi.um.entity
  global-config:
    #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: 0
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    #column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1

  #刷新mapper 调试神器
    refresh-mapper: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
apts:
  aptsFile:
    jarFiles: /apts/files/
    projectFiles: /apts/project/
